base:
    path: "/opt/batch/jacob/"
prod:
    postgres:
        username: "nxcobolbatch"
        password: ""
        url: ""
    db2:
        username: ""
        password: ""
        url: ""
    oracle:
        username: ""
        password: ""
        url: ""
coll:
    postgres:
        username: "nxcobolbatch"
        password: ""
        url: ""
    db2:
        username: ""
        password: ""
        url: ""
    oracle:
        username: "nxcobolbatch"
        password: ""
        url: ""
